### ISSUE TITLE
what version of tensorflow are you using?

### ISSUE THREAD

**Issue by arikint** [mbechtel2/DeepPicar-v2#4]

**Comment by ahmed1186** [comment]
The actual version of tensorflow doesn't matter that much as long as it's running in a python2 environment(for training) and python3 on the Pi for autonomous driving.
I got the training code working using tensorflow-gpu 1.5 on ubuntu, While the autonomous driving code is running on the Pi with tensorflow 1.9 in a python3 environment.

**Comment by mbechtel2** [comment]
While the TensorFlow version shouldn't make a difference, we have recently encountered problems with versions 1.12.0 and 1.13.1 on the Pi (the official pip packages appear to be broken). As such, we are currently using version 1.11.0, but all previous versions should also work.
